services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    ports:
      - "8080:8080"
    volumes:
      - ./docker/keycloak/provisioning:/opt/keycloak/data/import
      - ./src:/opt/keycloak/themes/kcw
    command: |
      start-dev
      --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
